name: Hello World
author: Ekram Touir
description: "Greet someone and recored time"
inputs:
    who_to_greet:
        description: "Who to greet"
        #required: true
        default: "World"
outputs:
    time:
        description: "time of the greeting"
runs:
    using: "docker"
   # image: '"docker"://node:18.16-alpine3.17'
    image: 'Dockerfile'
    #entrypoint
    args: 
      - ${{ inputs.who_to_greet }}
    env:
      HELLO: WORLD
    #post: '/cleanup.sh' 
    #post-if:
    #pre-if:
    #pre: 


