name: Send a Slack Message
author: Ekram Touir
description: "Send a slack message with workflow information"
inputs:
  slack_webhook:
    description: "Slack Webhook"
    required: true
  message:
    description: "Slack Message"
    required: true
runs:
   using: docker
   image: 'Dockerfile'
   args:   
     - ${{inputs.slack_webhook}}    # pass args to php script
     - ${{inputs.message}}

      