name: Cahce and Artificats
on: [workflow_dispatch]
jobs:
    use-axios:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Cache node_modules
              id: cache-dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{runner.os}}-npm-cache-${{hashFiles('**/package-lock.json')}} #update cache only when lock is change and so dependencies
                restore-keys: |
                   ${{runner.os}}-npm-cache-
                   ${{runner.os}}-
#search for all the cache the have the same caches star with that 
            - name: Display Cahce output
              run: echo '${{toJson(steps.cache-dependencies.outputs.cache-hit)}}'
            - name: install dependencies
              run: npm i 
            - name: Run Test
              run: npm test
            - name: Upload Code Coverage Report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                name: code-coverage
                path: coverage
                retention-days: 10  
            - name: use axios
              uses: actions/github-script@v6
              with:
                script: |
                 const axios = require('axios')
                 const res = await axios.get('https://icanhazdadjoke.com/', {headers:{Accept:'test/plain'}})
                 console.log(res.data)