name: Workflow Command 
on: [push]
jobs:
    testing-wf-coomands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"

