name: Concurrency 1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
concurrency: 
    group: concurrency-1 # can be used in a single job as well, running just one at a time cnat be in //
    cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30