name: DOCKER WORKFLOW
on: [workflow_dispatch]
jobs:
    docker-job:
        runs-on: ubuntu-latest
        #container: node:20.3-alpine3.17
        container:
            image: node:20.3-alpine3.17
            #credentials:
                #username:
                #password:
            env: 
                API_URL: some-url.com
            ports:
                - 80
           #volumes:
                   # - vol_name: /path/in/container
                    #- /path/to/container
                   # - path(in/host: /path/in/container
            #options: --cpus 1
        steps:
            - name: Log node and os versions
              run: |
               node -v
               cat /etc/os-release
            - name: Access to env
              run: |
               echo $API_URL // will be executed in runner machine
               echo ${{github.env.API_URL}}
            - name: Create a file
              run:   echo 'Some text' > text.txt 
            - name: Container in a step
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: '/usr/local/bin/node' # we can only a path to executable
                args: -p 2+3
            - name: Log Node Versio 
              uses: docker://node:18.16-alpine3.17
              with:
                  args: -v
            - name: Show file contents
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: text.txt
            - uses: actions/checkout@v3
            - name: Run a bash script
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: ./script.sh
                args: "some string" #two args some first and string second arg.
                 





    