name: External Events
on:
    repository_dispatch:
        types: ["buid"] # will run only of we sent event_type is build with REST API
jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{github.event.client_payload.env}}
