name: Matrix
on: [push]
jobs:
    node-matrix:
        continue-on-error: true # prevent a job from failing 
        strategy:
            matrix:
                node-version: [14, 15, 16]
                os: [ubuntu-latest, windows-latest]
                include: 
                    - os: ubuntu-latest
                      is-Ubuntu: true
                    - os: macos-latest
                      node-version: 13
                    - experimental: false   # added only to the original ones before includes
                    - os: ubuntu-latest
                      node-version: 16
                      experimental: true
                    - os: ubuntu-latest  # a new one will be added to the matrix as ubunu with this same node version
                      node-version: 17
                      experimental: true
                exclude: 
                    - os: ubuntu-latest
                      node-version: 16
                    
            #max-parallel: 3
            fail-fast: false # if any job fails, other will continue    
        runs-on: ${{matrix.os}}
        steps:
          - run: node -v
          - run: echo '${{toJson(matrix)}}'
          - uses: actions/setup-node@v3
            with:
              node-version: ${{matrix.node-version}}
          - run: node -v