name: Pull Request Comment
on:
  pull_request_target:
    types: [opened]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    permissions: #read-all read for all scopes write-all as well or {}
        issues: write
        #contents: read
    steps:
      - name: Comment on New PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Thanks for contributing!',
            });

#https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token            