name: Reusable Workflow From anywhere
on:
    workflow_call:
        inputs:
            name:
                description: ' Input Description'
                type: string
                default: 'Ekram'
                required: false
        secrets:
            access-token:
                description: 'Secret Description'
                required: true
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: ls -a
    log-context-and-inputs:
        runs-on: ubuntu-latest
        steps:
            - name: Display github context
              run: echo ' ${{ toJson(github) }} '
            - name: Display Input copntext  
              run: echo '${{toJson(inputs.name)}}'
            - name: Display access-token secret 
              run: echo '${{toJson(secrets.access-token)}}'

