name: action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
        - name: Simple JS Action
          #uses:  actions/hello-world-javascript-action@v1.1
          #uses:  actions/hello-world-javascript-action@main
          id: greet
          uses:  actions/hello-world-javascript-action@4eb553da6acf2ea2b2ed520bc2aaabf409213034
          with:
            who-to-greet: Ekram
        - name: Log Greeting Time
          run: echo "${{steps.greet.outputs.time}}"
