name: Reusing Reusable 
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Input Description'
                type: string
                default: 'Ekram'
                required: false
jobs:
    calling-a-reusable-wf:
        #runs-on: ubuntu-latest no need because it will run another workflow
        uses: ./.github/workflows/reusable.yml
        with:
            name: ${{inputs.name}}
        secrets:    
            access-token: ${{secrets.ACCESS_TOKEN}}

