name: Reusing Reusable 
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Input Description'
                type: string
                default: 'Ekram'
                required: false
jobs:
    calling-a-reusable-wf:
        #runs-on: ubuntu-latest no need because it will run another workflow
        uses: ./.github/workflows/reusable.yml
        with:
            name: ${{inputs.name}}
        secrets:    
            access-token: ${{secrets.ACCESS_TOKEN}}
    calling-reusable:
        uses: ./.github/workflows/reusable-workflow.yml
        secrets: inherit
    using-reusable-workfloe-output:
        runs-on: ubuntu-latest
        needs: calling-reusable
        steps:
            - run: echo ${{needs.calling-reusable.outputs.date}}

