name: First Workflow
on: [push]
jobs:
    run_shell-command: 
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run : echo "Hello Word"
        - name: multiline Command
          run: |
            node -v
            npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View SW version
              run: sw_vers
    dependent-job:
        runs-on: windows-latest
        needs: run_shell-command
        steps:
            - name:  echo string 
              run: Write-Output "Windows Strings"
            - name:  echo string 
              run: Write-Output "Windows Strings"